### PR TITLE
Fix mobile view

### LINKED ISSUE #103: Source code should look better on mobile
IMG_4126

The wrapping is annoying in this view. I think we should save space by removing line numbers.

Our code is 80 characters wide. Font size should be adjusted so that 80 columns can be displayed without scrolling horizontally.

### PR DESCRIPTION
**Pull request by j-f1**
Fixes #103.

- Ensure the code view is always at least 80 characters wide on mobile, and enable horizontal scrolling.
- Scroll the line numbers out of view on mobile, but allow the user to easily scroll them back in.

### CODE REVIEW

File: src/code_styles.js [hunk 1]
```diff
@@ -12,6 +14,17 @@ module.exports = function createStyle(maxNumberLength) {
...
       background: transparent;
+      -webkit-text-size-adjust: 100%;
+    }
+    @media ${breakpoint} {
+      pre {
+        width: 100vw;
+        overflow-x: scroll;
+      }
+      code.hljs {
+        width: calc(49em + ${maxNumberLength + 4}ex);
```
Comment (ry) [inline src/code_styles.js]: Where does the 49em come from? Add a comment?

File: src/code_scripts.js [hunk 2]
```diff
@@ -98,6 +100,25 @@ const selection = () => {
...
+
+  if (query.matches) {
+    pre.scrollLeft = scrollOffset;
+  }
+  query.onchange = ({ matches }) => {
+    if (matches) {
+      pre.scrollLeft += scrollOffset;
+    } else {
+      pre.scrollLeft -= scrollOffset;
+      if (pre.scrollLeft < 0) pre.scrollLeft = 0;
```
Comment (ry) [inline src/code_scripts.js]: Have you run "./format.sh" ?

File: src/code_scripts.js [hunk 3]
```diff
@@ -106,4 +131,7 @@ module.exports = /* HTML */ `
   <script>
     (${selection})();
   </script>
+  <script>
+    (${toggleNumbers})();
+  </script>
```
Comment (ry) [inline src/code_scripts.js]: In the future we should just load the JS files as a separate request, rather than including them in the HTML. Not necessary for this PR tho.

**Comment by j-f1** [comment]
Hold on for a second — I’m adding one more improvement

**Comment by j-f1** [comment]
Done!
